# .github/workflows/markdown-lint.yml
---
name: Markdown Lint
on:
  push:
    branches: ["main", "master", draft, draft*]
  pull_request:
    branches: ["main", "master"]

permissions: {}  # Setting default permissions to none for enhanced security

jobs:
  markdown-lint:
    permissions:
      contents: read
      statuses: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ripgrep yamllint gawk

      - name: Lint Workflow YAML
        run: |
          yamllint -f github .github/workflows/markdown-lint.yml

      - name: Run Markdown Lint Script
        shell: bash
        run: |
          ./.github/bin/markdown_list_action.bash
