# .github/workflows/yaml-lint.yml
---
name: YAML Lint
on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main", "master", draft, draft*]
  pull_request:
    branches: ["main", "master"]

permissions: {}  # Setting default permissions to none for enhanced security

jobs:
  yaml-lint:
    permissions:
      contents: read
      statuses: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Workflow YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/yaml-lint.yml
          config_file: .yamllint
          format: github
          no_warnings: true
        if: ${{ !caanceled() }}
      - name: Lint YAML Files
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ./.*.yaml ./*.yml ./**/*.yml
          config_file: .yamllint
          format: github
          no_warnings: true
        if: ${{ success() }}
